image: openjdk:8

cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
        - node_modules
        - .gradle/wrapper
        - .gradle/caches
stages:
    - build
    - test
    - package
    - release
    - deploy

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x gradlew
    - ./gradlew yarn_install -PnodeInstall --no-daemon

gradle-build:
    stage: build
    script:
        - ./gradlew compileJava -x check -PnodeInstall --no-daemon
gradle-test:
    stage: test
    script:
        - ./gradlew test -PnodeInstall --no-daemon
    artifacts:
        paths:
            - build/reports/tests/*
gradle-front-test:
    stage: test
    script:
        - ./gradlew yarn_test -PnodeInstall --no-daemon

gatling-test:
    stage: test
    allow_failure: true
    script:
        - ./gradlew gatlingRun -x cleanResources -PnodeInstall --no-daemon
    before_script:
        - export GRADLE_USER_HOME=`pwd`/.gradle
        - chmod +x gradlew
        - ./gradlew yarn_install -PnodeInstall --no-daemon
        - ./gradlew bootRun &
    artifacts:
        paths:
            - build/reports/gatling/*
gradle-repackage:
    stage: package
    script:
        - ./gradlew bootRepackage -Pprod -x check -PnodeInstall --no-daemon
    artifacts:
        paths:
            - build/libs/*.war
